### PR TITLE
Reduce the storage requirements for nodes & paths

### PR DESCRIPTION
**Pull request by asl**
* Store names in HAT-Trie
  * Use small vector for edges

### CODE REVIEW

**Comment by wafemand** [comment]
LGTM

**Comment by ekg** [comment]
What's the largest graph you're testing on?

**Comment by asl** [comment]
@ekg My current test is ~850Mb GFA uncompressed. 2.3 million nodes, 860k edges, 2 million paths. After all the changes we're having here it loads in ~10 seconds and the memory consumption is less than 3Gb. More to follow :)

**Comment by ekg** [comment]
Wow! How's it going with layout? Any performance tweaks?

**Comment by asl** [comment]
@ekg These all were deployed back in June: https://github.com/asl/BandageNG/releases/tag/v2022.06 including per-component multithreaded layout, newer (and faster) version of OGDF among other stuff. And subsequent releases also improved the situation here and there.

Are you seeing any issues / deficiencies on your end? Something particular you'd like to optimize? :)

**Pull request merged**
